# Generated by Django 3.2.7 on 2021-10-28 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_publication_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='file',
        ),
    ]
