# Generated by Django 3.2.7 on 2021-10-24 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_publication_short_description'),
        ('favorite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritelaw',
            name='law',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.law'),
        ),
        migrations.AlterField(
            model_name='favoritepublication',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.publication'),
        ),
    ]
